platform :ios, '18.0'

project 'ImageTranslateOCR.xcodeproj'

target 'ImageTranslateOCR' do
  use_frameworks! :linkage => :static
  pod 'GoogleMLKit/TextRecognitionChinese', '8.0.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
